language: go
go:
 - 1.6.x
 - 1.7.x
 - 1.8.x
 - 1.9.x
 - tip
gobuild_args: -tags no_pkg_config
dist: xenial
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get install bison flex automake autoconf libtool make gcc
  - wget --no-verbose -O- https://github.com/VirusTotal/yara/archive/v3.7.0.tar.gz | tar -C ${TRAVIS_BUILD_DIR} -xzf -
  - ( cd ${TRAVIS_BUILD_DIR}/yara-3.7.0 && ./bootstrap.sh && ./configure && make )
  - export CGO_CFLAGS=-I${TRAVIS_BUILD_DIR}/yara-3.7.0/libyara/include
  - export CGO_LDFLAGS=-L${TRAVIS_BUILD_DIR}/yara-3.7.0/libyara/.libs
  - export LD_LIBRARY_PATH=${TRAVIS_BUILD_DIR}/yara-3.7.0/libyara/.libs
